spring.application.name=orders-spring-boot

# logging #
logging.level.web=TRACE
# logging.level.web=DEBUG

# spring.output #
spring.output.ansi.enabled=detect

# server.port #
server.port=8081

# server.ssl #
server.ssl.enabled=false

# spring.messages #
spring.messages.basename=messages
spring.messages.encoding=UTF-8